

imageCredentials:
  registry:
    url: 571908524012.dkr.ecr.eu-north-1.amazonaws.com
    imagePullPolicy: IfNotPresent
    pullSecret: regcred
  repoPath: babtist  


images:
  server:
    name: m3uaserver
    tag: "{{ .Chart.Version }}"  
  client:
    name: m3uaclient
    tag: "{{ .Chart.Version }}"  


replicaCount: 
  server: 1
  client: 1

readinessProbe:
  # Number of seconds after the container has started before readiness probes are initiated.
  initialDelaySeconds: 2
  # How often (in seconds) to perform the probe.
  periodSeconds: 10
  # Number of seconds after which the probe times out.
  timeoutSeconds: 5
  # When a probe fails, Kubernetes will try failureThreshold times before giving up. In case of readiness probe the Pod will be marked Unready.
  failureThreshold: 3
  # Minimum consecutive successes for the probe to be considered successful after having failed.
  successThreshold: 1

livenessProbe:
  # Number of seconds after the container has started before liveness probes are initiated.
  initialDelaySeconds: 2
  # How often (in seconds) to perform the probe.
  periodSeconds: 60
  # Number of seconds after which the probe times out.
  timeoutSeconds: 5
  # When a probe fails, Kubernetes will try failureThreshold times before giving up. Giving up in case of liveness probe means restarting the container.
  failureThreshold: 6
  # Minimum consecutive successes for the probe to be considered successful after having failed.
  successThreshold: 1

client:
  config: 
    remoteHost: "{{ include \"sinch.cc2022.m3uatest.server.fullname\" . }}"
    remotePort: "2905"