# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
project_name: ccdemo
env_files:
  github_token: ~/.github/token_codecamp
before:
  hooks:
    - go mod tidy
    # This will log into to AWS.
    - aws ecr get-login-password | docker login -u AWS --password-stdin "https://$(aws sts get-caller-identity --query 'Account' --output text).dkr.ecr.$(aws configure get region).amazonaws.com"
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    id: ccdemo
    main: ./cmd/m3uaserver  
    binary: m3uaserver

release:
  disable: true

dockers:
  - image_templates: [ "571908524012.dkr.ecr.eu-north-1.amazonaws.com/babtist/m3uaserver:{{ .Tag }}"]
    dockerfile: docker/m3uaserver/Dockerfile
    goos: linux
    goarch: amd64
    ids:
    - m3uaserver
    skip_push: false
  