apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sinch.cc2022.m3uatest.client.fullname" . }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "sinch.cc2022.m3uatest.client.fullname" . }}
  replicas: {{ .Values.replicaCount.client }}
  template:
    metadata:
      labels:
{{ include "sinch.cc2022.m3uatest.client.labels" . | indent 8 }}
    spec:
      imagePullSecrets:
      - name: {{ .Values.imageCredentials.registry.pullSecret }}
      containers:
        - name: client
          image: {{ template "sinch.cc2022.m3uatest.registryUrl" . }}/{{ .Values.imageCredentials.repoPath }}/{{ .Values.images.client.name }}:{{ tpl .Values.images.client.tag . }}
          imagePullPolicy: {{ .Values.imageCredentials.registry.imagePullPolicy }}
          env:
          - name: REMOTE_IP
            value: "{{ tpl .Values.client.config.remoteHost . }}"
          - name: REMOTE_PORT
            value: "{{ tpl .Values.client.config.remotePort . }}"  
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 2905
              name: sctp
              protocol: SCTP  
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
         
      
