apiVersion: v1
kind: Service
metadata:
  name: {{ include "sinch.cc2022.m3uatest.server.fullname" . }}
  labels:
{{ include "sinch.cc2022.m3uatest.server.labels" .  | indent 4}}
spec:
  selector:
    app.kubernetes.io/name: {{ template "sinch.cc2022.m3uatest.server.fullname" . }}
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: sctp
      port: 2905
      protocol: SCTP
      targetPort: sctp  
  type: ClusterIP

